#==========================================================#
#    ______________          __  ____            _____     #
#   / ____/ __/ __/__  _____/ /_/ __ \________  / __(_)  __#
#  / __/ / /_/ /_/ _ \/ ___/ __/ /_/ / ___/ _ \/ /_/ / |/_/#
# / /___/ __/ __/  __/ /__/ /_/ ____/ /  /  __/ __/ />  <  #
#/_____/_/ /_/  \___/\___/\__/_/   /_/   \___/_/ /_/_/|_|  #
#     ╔═╗┌─┐┌┐┌┌─┐┬┌─┐┬ ┬┬─┐┌─┐┌┬┐┬┌─┐┌┐┌  ╔═╗┬┬  ┌─┐      #
#     ║  │ ││││├┤ ││ ┬│ │├┬┘├─┤ │ ││ ││││  ╠╣ ││  ├┤       #
#     ╚═╝└─┘┘└┘└  ┴└─┘└─┘┴└─┴ ┴ ┴ ┴└─┘┘└┘  ╚  ┴┴─┘└─┘      #
#==========================================================#
config: 1